import { Constructor } from '@open-wc/dedupe-mixin';
import { TemplateResult } from 'lit';
import { Directive } from 'lit/directive.js';

export { Constructor };

type TemplateName = string;
type RefName = string;
type RefDirective = Directive;

type LabelName = string;

type TemplateData = {
  /**
   * Ref directives are Lit directives that correspond to a certain element (usually a control) inside the component template.
   * This allows an Extending Developer to
   *
   * An example:
   *
   *
   */
  refDirectives: Record<RefName, RefDirective>;
  /**
   * Data contains an
   */
  data: object;
};

type PureTemplateFunction = (templateData: TemplateData) => TemplateResult;

type Templates = Record<TemplateName, PureTemplateFunction>;
type RefEntry = { elem: { value: Element }; name: RefName };
export type RefCollection = Array<RefEntry> & Record<RefName, Element>;

type Labels = Record<LabelName, string | Promise<string>>;

export declare class UIBaseElement {
  /**
   * Pure Templates™ are defined as functions on the `static templates` object of UIBaseElement.
   * The goal of these templates is to have a clear separaton between:
   * - ⚙️ functionality - the heavy lifting, defined by Lion
   * - 🎨 presentation - the unique look and feel for your design system, defined by the Extending Developer
   *
   * Functionality is defined by the Lion component via ref directives, whereas the presentation is defined by the Extending Developer.
   * This means that the Extending Developer is fully in control of the [visual identity](/develop/glossary#visual-identity) of the component.
   * The presentation consists of:
   * - HTML markup
   * - CSS styling
   * Together, they create three trees or object models:
   * - DOM tree (the markup)
   * - CSSOM tree (the styling)
   * - AOM tree (the semantics, needed for screen readers)
   * It's important that the AOM generated by the template from the Extending Developer is as intended. For instance, when
   *
   * ## Why a pure function?
   * By only allowing one TemplateData object as the input of our template we steer the Extending Developer in the right direction.
   * On top, we also prevent side effects.
   *
   * ## RefDirectives
   * The ref directives can be used to connect the functionality of a certain component. For instance, look at the [InputTelDropdown](components/api/InputTelDropdown) component.
   * It uses either [HTMLSelectElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement) or [LionSelectRich](components/api/LionSelectRich)
   * for the dropdown. In templateData, we find `refDirectives.dropdown`. This directive knows it's compatible with either `HTMLSelectElement` or `LionSelectRich`.
   * In case it's applied to HTMLSelectElement, it could listen for an input event, in case of a LionSelectRich, it could listen for a model-value-changed event.
   *
   * ```js
   * static templates = {
   *   ...
   *   dropdown: (templateData) => {
   *     const { directives } = templateData;
   *
   *     return html`<select ${directives.dropdown()}>...</select>`;
   *   },
   * }
   * ```
   *
   * The select now automatically is connected to the host component. The directive handles:
   * - communication via events
   * - communication via attributes and properties
   * - adding labels / localization based on the labels defined on the instance
   * - adding aria + id relationships
   * - calling methods on the ref component
   * - functional styling (like position/display properties)
   *
   * Note that when a directive is applied to the wrong element, an error is thrown.
   * Via linting, we can make sure that all the directives are applied and that they are applied to the right elements
   *
   * ## Relevant instance data
   * It can happen that the instance holds some data, usually lists/collections, that the template needs access to.
   *
   * ```js
   * static templates = {
   *   ...
   *   dropdown: (templateData) => {
   *     const { directives, data } = templateData;
   *
   *     return html`
   *       <select ${directives.dropdown()}>
   *         ${data.itemList.map((item) => html`<option>${item}</<option>`)}
   *       </select>`;
   *   },
   * }
   * ```
   *
   * ## How do I supply my own visual identity?
   *
   * There's three levels of customization:
   *
   * 1. Theme CSS properties of the default 'mnml' theme (when you want to change colors, spacings, border radii etc. and don't have an already existing design system)
   * 2. Decorate templates for existing components (when you have an existing design system, but want to re-use complete compositions built from lion components)
   *   - via `MyComponent.templates` constructor property
   *   - via `myComponentInstance.template` instance property
   * 3. Extend the component and provide your own templates (when you have an existing design system and want to create your own set of components)
   *
   * ## What about scoped elements?
   * We assume this is used in conjunction with ScopedElementsMixin. When a specific component is used, do:
   *
   * ```js
   * static scopedElements = {
   *   ...super.scopedElements,
   *   'my-select-rich': MySelectRich,
   * }
   * ```
   *
   * ## About accessibility
   * As stated above, we guarantee accessibility in two ways:
   * - behavior and labels ref directives
   * - semantics via markup. Via tests we should verify that the AOM tree remains as intended.
   */
  templates: Templates;
  /**
   * A RefCollection interface is comparable to the interface of [HTMLFormControlsCollection](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormControlsCollection),
   * in the sense that it's both accessible as array and object.
   * For a quick element reference, use:
   * ```js
   * this.refs.myRefName
   * ```
   */
  refs: RefCollection;
  /**
   * UI components should be localize system agnostic. This means
   */
  labels: Labels;
}
