// This is an auto-generated file containing flag exports.
// It is generated by updateFlagExports.js script and should not be edited manually.

export { default as AUFlag } from '../components/input-tel/flag-svgs-js/AU.js';
export { default as BEFlag } from '../components/input-tel/flag-svgs-js/BE.js';
export { default as DEFlag } from '../components/input-tel/flag-svgs-js/DE.js';
export { default as ESFlag } from '../components/input-tel/flag-svgs-js/ES.js';
export { default as ITFlag } from '../components/input-tel/flag-svgs-js/IT.js';
export { default as LUFlag } from '../components/input-tel/flag-svgs-js/LU.js';
export { default as NLFlag } from '../components/input-tel/flag-svgs-js/NL.js';
export { default as PHFlag } from '../components/input-tel/flag-svgs-js/PH.js';
export { default as PLFlag } from '../components/input-tel/flag-svgs-js/PL.js';
export { default as PLACEHOLDERFlag } from '../components/input-tel/flag-svgs-js/PLACEHOLDER.js';
export { default as ROFlag } from '../components/input-tel/flag-svgs-js/RO.js';
export { default as TRFlag } from '../components/input-tel/flag-svgs-js/TR.js';
