/**
 * THIS IS GENERATED FILE. PLEASE DO NOT EDIT IT MANUALLY
 * GENERATED BY `node scripts/localize.mjs`
 */
export const localizeNamespaceLoader = /** @param {string} locale */ locale => {
  switch (locale) {
    case 'bg-BG':
    case 'bg':
      return import('@lion/ui/input-range-translations/bg.js');
    case 'cs-CZ':
    case 'cs':
      return import('@lion/ui/input-range-translations/cs.js');
    case 'de-AT':
    case 'de-DE':
    case 'de':
      return import('@lion/ui/input-range-translations/de.js');
    case 'en-AU':
    case 'en-GB':
    case 'en-PH':
    case 'en-US':
    case 'en':
      return import('@lion/ui/input-range-translations/en.js');
    case 'es-ES':
    case 'es':
      return import('@lion/ui/input-range-translations/es.js');
    case 'fr-FR':
    case 'fr-BE':
    case 'fr':
      return import('@lion/ui/input-range-translations/fr.js');
    case 'hu-HU':
    case 'hu':
      return import('@lion/ui/input-range-translations/hu.js');
    case 'it-IT':
    case 'it':
      return import('@lion/ui/input-range-translations/it.js');
    case 'nl-BE':
    case 'nl-NL':
    case 'nl':
      return import('@lion/ui/input-range-translations/nl.js');
    case 'pl-PL':
    case 'pl':
      return import('@lion/ui/input-range-translations/pl.js');
    case 'ro-RO':
    case 'ro':
      return import('@lion/ui/input-range-translations/ro.js');
    case 'ru-RU':
    case 'ru':
      return import('@lion/ui/input-range-translations/ru.js');
    case 'sk-SK':
    case 'sk':
      return import('@lion/ui/input-range-translations/sk.js');
    case 'uk-UA':
    case 'uk':
      return import('@lion/ui/input-range-translations/uk.js');
    case 'zh-CN':
    case 'zh':
      return import('@lion/ui/input-range-translations/zh.js');
    default:
      return import('@lion/ui/input-range-translations/en.js');
  }
};
