/**
 * This file is automatically generated by token-renderer
 * Do not edit
 */

import { css } from 'lit';

export default css`
  :host {
    display: block;
    padding-bottom: 16px;
  }

  /** Showing/Hiding additional code blocks **/
  ::slotted(pre) {
    background-color: var(--neutral-color-darkest);
    margin-bottom: 0;
  }

  .demo-viewer {
    background-color: var(--neutral-color-lightest);
    border-radius: 16px;
  }

  .demo-viewer__section--modifier-combinator {
    padding-block: 16px;
    padding-inline: 24px;
  }

  .demo-viewer__section--demo {
    position: relative;
    padding-block-end: 24px;
    padding-inline: 24px;
    border-bottom-left-radius: inherit;
    border-bottom-right-radius: inherit;
  }

  .demo-viewer__inner-section {
    background-color: var(--page-background);
    padding: 24px;
  }

  .demo-viewer__section--code {
    position: relative;
    padding-block: 24px;
    padding-inline: 24px;
    background-color: var(--neutral-color-darkest);
    font-size: medium;
    border-bottom-left-radius: inherit;
    border-bottom-right-radius: inherit;
  }

  .icon-toolbar {
    display: flex;
    justify-content: end;
    gap: 6px;
  }

  .tools-btn {
    display: inline-flex;
    padding: 8px;
    border: 1px solid transparent;
    background: none;
    cursor: pointer;
    fill: var(--text-color);
    border-radius: 50%;
  }

  .tools-btn[aria-pressed='true'] {
    fill: var(--primary-icon-color);
  }

  .tools-btn:hover,
  .tools-btn[aria-pressed='true']:hover {
    background-color: var(--primary-icon-color);
    fill: white;
  }

  .tools-btn:focus {
    box-shadow: 0 0 0 2px white;
    outline-width: 2px;
    outline-style: solid;
    outline-color: black;
    outline-offset: 2px;
  }

  .tools-btn > svg {
    width: 20px;
    height: 20px;
  }

  .demo-viewer__section--code .icon-toolbar {
    position: absolute;
    top: 16px;
    right: 16px;
    margin: 0;
  }
`;
