/**
 * This file is automatically generated by token-renderer
 * Do not edit
 */

import { css } from 'lit';

export default css`
  :host {
    display: block;
    padding-bottom: 16px;
  }

  :host([device-mode]) slot[name='story'] {
    display: none;
  }

  :host(:not([device-mode])) .card {
    border-radius: var(--border-radius-default);
  }

  /** === frame ==== */
  iframe {
    border-width: 2px;
    border-style: solid;
    border-color: var(--highlight-color);
    box-shadow:
      0 0 2px 0 rgb(0 0 0 / 10%),
      0 2px 10px 0 rgb(0 0 0 / 16%);
  }

  .platform-size-controls {
    display: flex;
    justify-content: flex-start;
  }

  .platform-size-controls > * {
    margin-right: 25px;
  }

  [part='frame-description'] {
    margin-top: calc(4px * -1);
    margin-bottom: 8px;
    color: var(--text-primary);
    font-size: 12px;
    line-height: 1.33;
    text-align: right;
  }

  :host([theme='dark']) [part='frame-description'] {
    color: var(--text-primary);
  }

  /** === code ==== */
  .copy-button {
    margin-top: 8px;
    margin-bottom: 16px;
    float: right;
  }

  .settings-wrapper {
    display: grid;
    max-width: 650px;
    margin: 20px;
    grid-gap: 20px 40px;
    grid-template-columns: 1fr;
  }

  .settings-left-part {
    margin-bottom: 20px;
  }

  @media (width >= 640px) {
    .settings-wrapper {
      grid-template-columns: repeat(2, 1fr);
    }
  }

  .settings-wrapper h3 {
    margin: 8px 0;
    font-size: 1rem;
    line-height: 1.5rem;
  }

  .options {
    margin: 16px 0;
  }

  .controls {
    display: flex;
    justify-content: right;
  }

  h4 {
    margin-top: 0;
    margin-bottom: 4px;
    color: var(--text-primary);
    font-size: 1rem;
    font-weight: normal;
    line-height: 1.5rem;
  }

  select {
    display: block;
    width: 100%;
    height: 40px;
    color: var(--text-primary);
    fill: var(--text-primary);
    font-size: 1rem;
    line-height: 1.5rem;
  }

  /** Showing/Hiding additional code blocks **/
  ::slotted(pre) {
    display: none;
  }

  :host([platform='web']) ::slotted(pre:nth-child(1)) {
    display: block;
  }
  :host([platform='android']) ::slotted(pre:nth-child(2)) {
    display: block;
  }
  :host([platform='ios']) ::slotted(pre:nth-child(3)) {
    display: block;
  }
  :host(:not([device-mode])) #wrapper {
    padding: 32px;
    border-width: 1px;
    border-color: var(--border-color);
  }
`;
